async (page) => {
  const context = page.context();
  const ui = context.pages().find(p => p.url().startsWith('chrome-extension://'));
  if (!ui) throw new Error('请先在 Seen 测试浏览器中打开历史页');
  const rpc = message => ui.evaluate(message => chrome.runtime.sendMessage(message), message);
  const checks = [];
  const assert = (condition, label) => { if (!condition) throw new Error(label); checks.push(label); };
  await rpc({ type: 'clear' });
  await rpc({ type: 'settings', settings: { paused: false, theme: 'dark' } });
  const cover = 'https://pbs.twimg.com/media/seen-test-cover.png';
  await context.route(cover, route => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="400"><rect width="1000" height="400" fill="#176685"/><text x="80" y="225" font-family="sans-serif" font-size="70" fill="white">Seen Article</text></svg>' }));
  await context.route('https://x.com/seen-inline-fixture', route => route.fulfill({ contentType: 'text/html; charset=utf-8', body: `<!doctype html><html><head><meta charset="utf-8"><title>Seen inline regression</title><style>body{margin:0;background:#000;color:white;font:16px sans-serif}main{width:600px;margin:20px auto}article{height:430px}img{width:100%;height:180px;object-fit:cover}</style></head><body><main><article data-testid="tweet"><div data-testid="User-Name"><a href="/tester">测试作者</a><a href="/tester">@tester</a><a href="/tester/status/8888800000001"><time datetime="2026-09-10T12:00:00Z">昨天</time></a></div><div data-testid="tweetText">文章前的说明文字应该保留</div><div><div data-testid="article-cover-image"><img alt="文章封面图片" src="${cover}"></div><div><div dir="auto">文章封面回归测试</div><div dir="auto">这是一段用于验证封面、标题和摘要的文章描述。</div></div></div></article><article data-testid="tweet"><div data-testid="User-Name"><a href="/tester">测试作者</a><a href="/tester/status/8888800000002"><time datetime="2026-09-10T12:00:00Z">昨天</time></a></div><div data-testid="tweetText">带图片的普通帖子</div><div data-testid="tweetPhoto"><img src="${cover}" alt="测试图片"></div></article></main></body></html>` }));
  const fixture = await context.newPage();
  await fixture.setViewportSize({ width: 1440, height: 1000 });
  await fixture.goto('https://x.com/seen-inline-fixture');
  await fixture.bringToFront();
  await fixture.waitForTimeout(2200);
  const rows = (await rpc({ type: 'export-page' })).posts;
  const article = rows.find(p => p.id === '8888800000001');
  assert(article?.article?.title === '文章封面回归测试' && article.article.cover === cover, '停留采集保存文章封面、标题与摘要');
  await fixture.locator('#seen-history-widget .toggle').click();
  await fixture.waitForSelector('#seen-history-widget .article-card');
  assert(await fixture.locator('#seen-history-widget .text').filter({ hasText: '文章前的说明文字' }).count() === 1, '文章卡片前保留原帖正文');
  assert(await fixture.locator('#seen-history-widget .media-grid img').count() === 1, '普通图片帖显示预览');
  await fixture.locator('#seen-history-widget .search input').fill('文章封面回归');
  await fixture.waitForFunction(() => document.querySelector('#seen-history-widget .count').textContent === '1 条记录');
  assert(await fixture.locator('#seen-history-widget .article-card').count() === 1, '文章标题可搜索并保留卡片展示');
  await fixture.locator('#seen-history-widget .open').hover();
  assert(await fixture.locator('#seen-history-widget .open').evaluate(e => getComputedStyle(e).textDecorationLine) === 'none', '链接悬浮没有下划线');
  const metrics = await fixture.locator('#seen-history-widget .panel').evaluate(e => ({ shadow: getComputedStyle(e).boxShadow, top: e.getBoundingClientRect().top, bottom: e.getBoundingClientRect().bottom }));
  assert(metrics.shadow !== 'none' && metrics.top >= 0 && metrics.bottom <= 1000, '弹层有阴影且完整位于桌面视口');
  assert(await fixture.locator('#seen-history-widget .list').evaluate(e => getComputedStyle(e).scrollbarWidth) === 'thin', '列表使用细滚动条');
  await fixture.locator('#seen-history-widget .filter-from').fill('2026-09-12T12:00');
  await fixture.locator('#seen-history-widget .filter-to').fill('2026-09-10T12:00');
  await fixture.waitForFunction(() => !document.querySelector('#seen-history-widget .error').hidden);
  assert((await fixture.locator('#seen-history-widget .error').textContent()).includes('开始时间'), '反向时间范围显示错误');
  await fixture.locator('#seen-history-widget .filter-reset').click();
  await fixture.waitForFunction(() => document.querySelector('#seen-history-widget .error').hidden && document.querySelector('#seen-history-widget .count').textContent === '2 条记录');
  assert(await fixture.locator('#seen-history-widget .card').count() === 2, '修正筛选后可继续搜索，不会卡住加载');
  await fixture.screenshot({ path: 'output/playwright/inline-article.png' });
  await fixture.locator('body').click({ position: { x: 40, y: 40 } });
  assert(!await fixture.locator('#seen-history-widget .panel').isVisible(), '点击弹层外部关闭');
  await fixture.locator('#seen-history-widget .toggle').click();
  await fixture.waitForSelector('#seen-history-widget .article-card');
  assert(await fixture.locator('#seen-history-widget .article-card').count() === 1, '再次打开正常展示文章卡片');
  await ui.bringToFront(); await ui.reload();
  await ui.waitForSelector('.article-card');
  assert(await ui.locator('.article-card .article-title').textContent() === '文章封面回归测试', '完整历史页同步显示文章卡片');
  await fixture.close();
  return { checks };
}
